openapi: 3.0.3
info:
  title: item-contract
  description: item
  version: 1.0.0
paths:
  /:

components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
  
