spring:
  datasource:
    password: resat123
    username: postgres
    url: jdbc:postgresql://localhost:5432/tattoo_artist
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
logging:
  level:
    root: info
