spring:
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    url: jdbc:h2:file:./demodb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: update
  liquibase:
    enabled: true
    change-log: classpath:/db.changelog-test/db.changelog-master-test.yaml
  elasticsearch-test:
    uris: localhost:9201
